message: Hello World from Netflix Stack!

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    registryFetchIntervalSeconds: 30
    initialInstanceInfoReplicationIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/eureka
  instance:
    preferIpAddress: true
    leaseExpirationDurationInSeconds: 60
